name: zealgrid
description: A Flutter package that simplifies accessing and retrieving data from a Firebase Realtime Database using a hierarchical path structure. Zealgrid provides dynamic getter methods and automatic data caching for efficient data retrieval.
version: 1.0.0
homepage: https://github.com/manipoint
repository: https://github.com/Zealtouch/zealgrid

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_database: ^11.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
